use super::context::{array_layout_macro_name, CCodegenContext};
use super::expr_emit::expr_to_c;
use super::external::collect_external_calls_with_signature;
use super::emit_residual;
use super::ArgKind;
use crate::ast::{Equation, Expression};
use std::collections::{HashMap, HashSet};
use std::io::Write;

pub fn emit_jacobian(
    jac_dense: &[Vec<Expression>],
    ctx: &CCodegenContext<'_>,
    out: &mut dyn Write,
) -> Result<(), String> {
    let n = jac_dense.len();
    writeln!(
        out,
        "void jacobian(double t, const double* x, const double* p, double* J) {{"
    )
    .map_err(|e| e.to_string())?;
    for (i, row) in jac_dense.iter().enumerate() {
        for (j, expr) in row.iter().enumerate() {
            let c_expr = expr_to_c(expr, &ctx)?;
            writeln!(out, "  J[{} * {} + {}] = {};", i, n, j, c_expr).map_err(|e| e.to_string())?;
        }
    }
    writeln!(out, "}}").map_err(|e| e.to_string())?;
    Ok(())
}

pub fn emit_header(
    has_jacobian: bool,
    state_array_layout: Option<&[(String, usize, usize)]>,
    output_array_layout: Option<&[(String, usize, usize)]>,
    param_array_layout: Option<&[(String, usize, usize)]>,
    out: &mut dyn Write,
) -> Result<(), String> {
    writeln!(out, "/* Generated by rustmodlica CG1-1. */").map_err(|e| e.to_string())?;
    writeln!(out, "#ifndef MODEL_H").map_err(|e| e.to_string())?;
    writeln!(out, "#define MODEL_H").map_err(|e| e.to_string())?;
    if let Some(layout) = state_array_layout {
        writeln!(out, "/* CG1-4: state x[] array layout */").map_err(|e| e.to_string())?;
        for (name, start, size) in layout {
            let mac = array_layout_macro_name(name);
            writeln!(out, "#define {}_START {}", mac, start).map_err(|e| e.to_string())?;
            writeln!(out, "#define {}_SIZE {}", mac, size).map_err(|e| e.to_string())?;
        }
    }
    if let Some(layout) = output_array_layout {
        writeln!(out, "/* CG1-4: output y[] array layout */").map_err(|e| e.to_string())?;
        for (name, start, size) in layout {
            let mac = array_layout_macro_name(name);
            writeln!(out, "#define Y_{}_START {}", mac, start).map_err(|e| e.to_string())?;
            writeln!(out, "#define Y_{}_SIZE {}", mac, size).map_err(|e| e.to_string())?;
        }
    }
    if let Some(layout) = param_array_layout {
        writeln!(out, "/* CG1-4: parameter p[] array layout */").map_err(|e| e.to_string())?;
        for (name, start, size) in layout {
            let mac = array_layout_macro_name(name);
            writeln!(out, "#define P_{}_START {}", mac, start).map_err(|e| e.to_string())?;
            writeln!(out, "#define P_{}_SIZE {}", mac, size).map_err(|e| e.to_string())?;
        }
    }
    writeln!(
        out,
        "void residual(double t, const double* x, double* xdot, const double* p, double* y);"
    )
    .map_err(|e| e.to_string())?;
    if has_jacobian {
        writeln!(
            out,
            "void jacobian(double t, const double* x, const double* p, double* J);"
        )
        .map_err(|e| e.to_string())?;
    }
    writeln!(out, "#endif").map_err(|e| e.to_string())?;
    Ok(())
}

pub fn emit_c_files(
    dir: &std::path::Path,
    state_vars: &[String],
    param_vars: &[String],
    output_vars: &[String],
    sorted_eqs: &[Equation],
    ode_jacobian: Option<&[Vec<Expression>]>,
    state_array_layout: Option<&[(String, usize, usize)]>,
    output_array_layout: Option<&[(String, usize, usize)]>,
    param_array_layout: Option<&[(String, usize, usize)]>,
    external_c_names: Option<HashMap<String, String>>,
    external_names: Option<&HashSet<String>>,
    user_function_bodies: Option<&HashMap<String, (Vec<String>, Expression)>>,
) -> Result<Vec<std::path::PathBuf>, String> {
    std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    let c_path = dir.join("model.c");
    let h_path = dir.join("model.h");
    let mut c_file = std::fs::File::create(&c_path).map_err(|e| e.to_string())?;
    let mut h_file = std::fs::File::create(&h_path).map_err(|e| e.to_string())?;
    let mut ctx = CCodegenContext::new(state_vars, param_vars, output_vars).with_layouts(
        state_array_layout,
        output_array_layout,
        param_array_layout,
    );
    if let Some(ref m) = external_c_names {
        ctx.external_c_names = Some(m.clone());
    }
    let external_sigs: HashMap<String, Vec<ArgKind>> =
        collect_external_calls_with_signature(sorted_eqs, &ctx);
    if !external_sigs.is_empty() {
        ctx.external_fns = Some(external_sigs.keys().cloned().collect());
    }
    emit_residual(
        state_vars,
        param_vars,
        output_vars,
        sorted_eqs,
        &ctx,
        &external_sigs,
        external_names,
        user_function_bodies,
        &mut c_file,
    )?;
    if let Some(jac) = ode_jacobian {
        emit_jacobian(jac, &ctx, &mut c_file)?;
    }
    emit_header(
        ode_jacobian.is_some(),
        state_array_layout,
        output_array_layout,
        param_array_layout,
        &mut h_file,
    )?;
    Ok(vec![c_path, h_path])
}
