use anyhow::{bail, Context, Result};
use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};

use crate::commands::OutputFormat;

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct ScopeResolved {
    pub name: String,
    pub desc: String,
    pub config_path: PathBuf,
    pub data_root: Option<PathBuf>,
    pub workers: Option<usize>,
    pub format: OutputFormat,
    pub progress: bool,
}

#[derive(Debug, Clone)]
pub struct ScopeSpec {
    pub name: &'static str,
    pub desc: &'static str,
    pub source: ScopeSource,
}

#[derive(Debug, Clone)]
pub enum ScopeSource {
    StaticConfig { path: &'static str },
    GeneratedPs1 { key: &'static str },
}

pub fn list_scopes() -> Vec<ScopeSpec> {
    vec![
        ScopeSpec {
            name: "smoke",
            desc: "Small smoke config.",
            source: ScopeSource::StaticConfig {
                path: "crates/regress-harness/examples/smoke.json",
            },
        },
        ScopeSpec {
            name: "testlib",
            desc: "TestLib set exported from PowerShell (pre-generated example).",
            source: ScopeSource::StaticConfig {
                path: "crates/regress-harness/examples/testlib_from_run_regression.json",
            },
        },
        ScopeSpec {
            name: "jit_phase1",
            desc: "JIT phase1 regression example.",
            source: ScopeSource::StaticConfig {
                path: "crates/regress-harness/examples/jit_phase1_from_run_regression.json",
            },
        },
        ScopeSpec {
            name: "mos",
            desc: "MOS regression exported from PowerShell (pre-generated example).",
            source: ScopeSource::StaticConfig {
                path: "crates/regress-harness/examples/mos_from_run_mos_regression.json",
            },
        },
        ScopeSpec {
            name: "with_omc_compare",
            desc: "Run with OMC compare enabled.",
            source: ScopeSource::StaticConfig {
                path: "crates/regress-harness/examples/with_omc_compare.json",
            },
        },
        ScopeSpec {
            name: "ps1_testlib",
            desc: "Generated by parsing run_regression.ps1 (cases + extra args).",
            source: ScopeSource::GeneratedPs1 { key: "ps1_testlib" },
        },
        ScopeSpec {
            name: "ps1_mos",
            desc: "Generated by parsing jit-compiler/scripts/run_mos_regression.ps1 (mos cases).",
            source: ScopeSource::GeneratedPs1 { key: "ps1_mos" },
        },
    ]
}

fn try_read_regression_data_root(config_path: &Path) -> Option<PathBuf> {
    let text = fs::read_to_string(config_path).ok()?;
    let v: Value = serde_json::from_str(&text).ok()?;
    let p = v
        .get("defaults")
        .and_then(|d| d.get("regression_data_root"))
        .and_then(|x| x.as_str())
        .or_else(|| {
            v.get("defaults")
                .and_then(|d| d.get("regression_data_root"))
                .and_then(|x| x.as_str())
        })?;
    if p.trim().is_empty() {
        None
    } else {
        Some(PathBuf::from(p))
    }
}

pub fn resolve_scope(repo_root: &Path, name: &str) -> Result<ScopeResolved> {
    let n = name.trim().to_ascii_lowercase();
    let Some(spec) = list_scopes()
        .into_iter()
        .find(|s| s.name.eq_ignore_ascii_case(n.as_str()))
    else {
        bail!("unknown scope: {name}");
    };

    let config_path = match spec.source {
        ScopeSource::StaticConfig { path } => repo_root.join(path),
        ScopeSource::GeneratedPs1 { key } => crate::ps1_profiles::ensure_profile(repo_root, key)?
            .with_context(|| format!("ps1 profile not available: {key}"))?,
    };

    let data_root = try_read_regression_data_root(&config_path);

    Ok(ScopeResolved {
        name: spec.name.to_string(),
        desc: spec.desc.to_string(),
        config_path,
        data_root,
        workers: None,
        format: OutputFormat::Human,
        progress: true,
    })
}

