//! Multi-model AOT archive format (Phase 4 of Leyden-inspired compilation).
//!
//! Bundles multiple model native code entries into a single persistent archive file.
//! Analogous to Leyden's AOT Cache, which stores pre-compiled methods and constant
//! pool data in a single memory-mapped file for near-zero startup.
//!
//! Archive layout:
//!   [Header][TOC Entry 0][TOC Entry 1]...[TOC Entry N][Code 0][Code 1]...[Code N]
//!
//! Each TOC entry maps a model's codegen cache key to its code offset and size
//! within the archive. The code section contains PIC (position-independent) object
//! files generated by Cranelift.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use crate::cache::build_id::binary_build_id;
use crate::cache::cache_scope::CacheScope;
use crate::flatten::flatten_cache::{flatten_cache_dir, std_cache_root, user_cache_root};

/// Composite fingerprint stamped into [`AotArchiveHeader::compiler_version`]. Format:
/// `<CARGO_PKG_VERSION>|<binary_build_id>`. The load path rejects archives with any other
/// string, so rewriting `rustmodlica.exe` invalidates the entire archive (per tier) on the
/// next process start rather than silently loading native code built by the previous
/// binary — the classic "warm AOT archive -> STATUS_ACCESS_VIOLATION" trap.
pub fn aot_archive_compiler_fingerprint() -> String {
    format!(
        "{}|{}",
        crate::cache::ir_epoch::COMPILER_VERSION,
        binary_build_id()
    )
}

const AOT_ARCHIVE_PROJECT: &str = "aot_archive-project.bin";
const AOT_ARCHIVE_USER: &str = "aot_archive-user.bin";
const AOT_ARCHIVE_STD: &str = "aot_archive-std.bin";
const AOT_ARCHIVE_LEGACY: &str = "aot_archive.bin";

/// When `RUSTMODLICA_AOT_NATIVE_LOAD` is `0`, `false`, or `no`, skip loading `calc_derivs` from the
/// default `aot_archive.bin` under the flatten cache root (artifact fast-path, sim-bundle path,
/// and full compile). In-process JIT compilation is used instead.
pub fn aot_default_archive_native_load_enabled() -> bool {
    static ENABLED: OnceLock<bool> = OnceLock::new();
    *ENABLED.get_or_init(|| match std::env::var("RUSTMODLICA_AOT_NATIVE_LOAD") {
        Ok(v) => {
            let t = v.trim();
            if t == "0" || t.eq_ignore_ascii_case("false") || t.eq_ignore_ascii_case("no") {
                return false;
            }
            true
        }
        Err(_) => true,
    })
}

const AOT_ARCHIVE_MAGIC: &[u8; 8] = b"RMJITAOT";
/// v2: TOC entries include `when_count` / `crossings_count` for AOT native load without JIT.
/// v3: bumped in sync with `CODEGEN_CACHE_VERSION=5` / tiered lookup fix. Existing archives
/// produced by older binaries are rejected with "version mismatch" to avoid loading stale
/// native code that can trigger Windows access violations during simulation.
const AOT_ARCHIVE_VERSION: u32 = 3;

/// Header at the start of an AOT archive file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AotArchiveHeader {
    pub version: u32,
    pub entry_count: u32,
    pub toc_size_bytes: u64,
    pub code_size_bytes: u64,
    pub compiler_version: String,
    pub target_triple: String,
}

/// Table-of-contents entry for one model in the archive.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AotTocEntry {
    pub model_name: String,
    pub codegen_key_hash: String,
    pub code_offset: u64,
    pub code_size: u64,
    pub symbol_count: u32,
    /// Import symbols needed by this code blob (resolved at load time).
    pub import_symbols: Vec<String>,
    pub when_count: u32,
    pub crossings_count: u32,
}

/// In-memory representation of a loaded AOT archive.
pub struct AotArchive {
    pub header: AotArchiveHeader,
    pub toc: Vec<AotTocEntry>,
    entries: HashMap<String, usize>,
    code_data: Vec<u8>,
}

impl AotArchive {
    /// Create a new empty archive for building.
    pub fn new_builder() -> AotArchiveBuilder {
        AotArchiveBuilder {
            entries: Vec::new(),
        }
    }

    /// Load an archive from a file.
    pub fn load(path: &Path) -> Result<Self, String> {
        let data = std::fs::read(path)
            .map_err(|e| format!("read aot archive: {}", e))?;
        Self::from_bytes(&data)
    }

    /// Parse an archive from raw bytes.
    pub fn from_bytes(data: &[u8]) -> Result<Self, String> {
        if data.len() < 8 {
            return Err("aot archive too small".into());
        }
        if &data[..8] != AOT_ARCHIVE_MAGIC {
            return Err("invalid aot archive magic".into());
        }

        let header_len_bytes = &data[8..12];
        let header_len = u32::from_le_bytes(
            header_len_bytes
                .try_into()
                .map_err(|_| "header length read failed")?,
        ) as usize;

        if data.len() < 12 + header_len {
            return Err("aot archive truncated at header".into());
        }

        let header: AotArchiveHeader =
            bincode::deserialize(&data[12..12 + header_len])
                .map_err(|e| format!("header deserialize: {}", e))?;

        if header.version != AOT_ARCHIVE_VERSION {
            return Err(format!(
                "version mismatch: got {} expected {} (remove or regenerate aot_archive.bin)",
                header.version, AOT_ARCHIVE_VERSION
            ));
        }

        let expected_triple = format!("{}-{}", std::env::consts::ARCH, std::env::consts::OS);
        if !header.target_triple.is_empty() && header.target_triple != expected_triple {
            return Err(format!(
                "target triple mismatch: archive={} host={} (regenerate aot_archive.bin)",
                header.target_triple, expected_triple
            ));
        }
        let expected_compiler = aot_archive_compiler_fingerprint();
        if !header.compiler_version.is_empty() && header.compiler_version != expected_compiler {
            return Err(format!(
                "compiler version mismatch: archive={} host={} (regenerate aot_archive.bin)",
                header.compiler_version, expected_compiler
            ));
        }

        let toc_start = 12 + header_len;
        let toc_end = toc_start + header.toc_size_bytes as usize;
        if data.len() < toc_end {
            return Err("aot archive truncated at toc".into());
        }

        let toc: Vec<AotTocEntry> =
            bincode::deserialize(&data[toc_start..toc_end])
                .map_err(|e| format!("toc deserialize: {}", e))?;

        let code_start = toc_end;
        let code_end = code_start + header.code_size_bytes as usize;
        if data.len() < code_end {
            return Err("aot archive truncated at code".into());
        }

        let code_data = data[code_start..code_end].to_vec();

        let mut entries = HashMap::new();
        for (i, entry) in toc.iter().enumerate() {
            entries.insert(entry.codegen_key_hash.clone(), i);
        }

        Ok(Self {
            header,
            toc,
            entries,
            code_data,
        })
    }

    /// Look up a code blob by codegen key hash.
    pub fn get_code(&self, codegen_key_hash: &str) -> Option<&[u8]> {
        let idx = self.entries.get(codegen_key_hash)?;
        let entry = &self.toc[*idx];
        let start = entry.code_offset as usize;
        let end = start + entry.code_size as usize;
        if end <= self.code_data.len() {
            Some(&self.code_data[start..end])
        } else {
            None
        }
    }

    /// Get the TOC entry for a model by codegen key hash.
    pub fn get_toc_entry(&self, codegen_key_hash: &str) -> Option<&AotTocEntry> {
        let idx = self.entries.get(codegen_key_hash)?;
        Some(&self.toc[*idx])
    }

    /// List all model names in the archive.
    pub fn model_names(&self) -> Vec<&str> {
        self.toc.iter().map(|e| e.model_name.as_str()).collect()
    }

    /// TOC entry for this model when the stable codegen key hash matches.
    pub fn lookup_entry(&self, model_name: &str, codegen_key_hash: &str) -> Option<&AotTocEntry> {
        self.toc.iter().find(|e| {
            e.model_name == model_name && e.codegen_key_hash == codegen_key_hash
        })
    }

    /// Default archive path within the project flatten cache directory.
    pub fn default_archive_path() -> Option<PathBuf> {
        flatten_cache_dir().map(|root| root.join(AOT_ARCHIVE_LEGACY))
    }

    /// Tier-split archive path for writes and primary reads.
    pub fn archive_path_for_scope(scope: CacheScope) -> Option<PathBuf> {
        let base = match scope {
            CacheScope::GlobalStd => std_cache_root().or_else(flatten_cache_dir)?,
            CacheScope::UserExt => user_cache_root().or_else(flatten_cache_dir)?,
            CacheScope::Project => flatten_cache_dir()?,
        };
        let name = match scope {
            CacheScope::GlobalStd => AOT_ARCHIVE_STD,
            CacheScope::UserExt => AOT_ARCHIVE_USER,
            CacheScope::Project => AOT_ARCHIVE_PROJECT,
        };
        Some(base.join(name))
    }
}

fn try_load_archive(path: &Path) -> Option<AotArchive> {
    if !path.is_file() {
        return None;
    }
    AotArchive::load(path).ok()
}

/// Loaded tier AOT archives (project, user extension, global std). Lookup follows that order.
pub struct AotArchiveSet {
    project: Option<AotArchive>,
    user: Option<AotArchive>,
    global_std: Option<AotArchive>,
}

impl AotArchiveSet {
    /// Load split archives plus legacy `aot_archive.bin` fallbacks under each tier root.
    pub fn load_tiered() -> Option<Self> {
        let project = flatten_cache_dir().and_then(|r| {
            try_load_archive(&r.join(AOT_ARCHIVE_PROJECT))
                .or_else(|| try_load_archive(&r.join(AOT_ARCHIVE_LEGACY)))
        });
        let user = user_cache_root().and_then(|r| {
            try_load_archive(&r.join(AOT_ARCHIVE_USER))
                .or_else(|| try_load_archive(&r.join(AOT_ARCHIVE_LEGACY)))
        });
        let global_std = std_cache_root().and_then(|r| {
            try_load_archive(&r.join(AOT_ARCHIVE_STD))
                .or_else(|| try_load_archive(&r.join(AOT_ARCHIVE_LEGACY)))
        });
        if project.is_none() && user.is_none() && global_std.is_none() {
            return None;
        }
        Some(Self {
            project,
            user,
            global_std,
        })
    }

    pub fn lookup_entry(&self, model_name: &str, codegen_key_hash: &str) -> Option<&AotTocEntry> {
        self.project
            .as_ref()
            .and_then(|a| a.lookup_entry(model_name, codegen_key_hash))
            .or_else(|| {
                self.user
                    .as_ref()
                    .and_then(|a| a.lookup_entry(model_name, codegen_key_hash))
            })
            .or_else(|| {
                self.global_std
                    .as_ref()
                    .and_then(|a| a.lookup_entry(model_name, codegen_key_hash))
            })
    }

    /// Same as [`Self::lookup_entry`], then read the code slice from the **same** archive that
    /// matched. [`Self::get_code`] must not be used after a tiered lookup: another tier may map
    /// the same stable hash to a different model's object, which would load the wrong native code.
    pub fn lookup_entry_with_blob(
        &self,
        model_name: &str,
        codegen_key_hash: &str,
    ) -> Option<(&[u8], &AotTocEntry)> {
        if let Some(a) = &self.project {
            if let Some(ent) = a.lookup_entry(model_name, codegen_key_hash) {
                let blob = a.get_code(codegen_key_hash)?;
                return Some((blob, ent));
            }
        }
        if let Some(a) = &self.user {
            if let Some(ent) = a.lookup_entry(model_name, codegen_key_hash) {
                let blob = a.get_code(codegen_key_hash)?;
                return Some((blob, ent));
            }
        }
        if let Some(a) = &self.global_std {
            if let Some(ent) = a.lookup_entry(model_name, codegen_key_hash) {
                let blob = a.get_code(codegen_key_hash)?;
                return Some((blob, ent));
            }
        }
        None
    }

    pub fn get_code(&self, codegen_key_hash: &str) -> Option<&[u8]> {
        self.project
            .as_ref()
            .and_then(|a| a.get_code(codegen_key_hash))
            .or_else(|| self.user.as_ref().and_then(|a| a.get_code(codegen_key_hash)))
            .or_else(|| {
                self.global_std
                    .as_ref()
                    .and_then(|a| a.get_code(codegen_key_hash))
            })
    }

    pub fn model_names(&self) -> Vec<&str> {
        let mut v = Vec::new();
        for a in [&self.project, &self.user, &self.global_std] {
            if let Some(ar) = a {
                for n in ar.model_names() {
                    if !v.iter().any(|x| *x == n) {
                        v.push(n);
                    }
                }
            }
        }
        v
    }
}

/// Builder for constructing a new AOT archive.
pub struct AotArchiveBuilder {
    entries: Vec<(AotTocEntry, Vec<u8>)>,
}

impl AotArchiveBuilder {
    pub fn add_model(
        &mut self,
        model_name: &str,
        codegen_key_hash: &str,
        code: Vec<u8>,
        import_symbols: Vec<String>,
        when_count: u32,
        crossings_count: u32,
    ) {
        let entry = AotTocEntry {
            model_name: model_name.to_string(),
            codegen_key_hash: codegen_key_hash.to_string(),
            code_offset: 0,
            code_size: code.len() as u64,
            symbol_count: import_symbols.len() as u32,
            import_symbols,
            when_count,
            crossings_count,
        };
        self.entries.push((entry, code));
    }

    /// Build and write the archive to a file.
    pub fn write_to_file(mut self, path: &Path) -> Result<(), String> {
        let bytes = self.build()?;
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("create dir: {}", e))?;
        }
        std::fs::write(path, bytes).map_err(|e| format!("write archive: {}", e))
    }

    /// Build the archive into raw bytes.
    pub fn build(&mut self) -> Result<Vec<u8>, String> {
        let mut code_section = Vec::new();
        for (entry, code) in &mut self.entries {
            entry.code_offset = code_section.len() as u64;
            entry.code_size = code.len() as u64;
            code_section.extend_from_slice(code);
        }

        let toc: Vec<AotTocEntry> = self.entries.iter().map(|(e, _)| e.clone()).collect();
        let toc_bytes =
            bincode::serialize(&toc).map_err(|e| format!("toc serialize: {}", e))?;

        let header = AotArchiveHeader {
            version: AOT_ARCHIVE_VERSION,
            entry_count: self.entries.len() as u32,
            toc_size_bytes: toc_bytes.len() as u64,
            code_size_bytes: code_section.len() as u64,
            compiler_version: aot_archive_compiler_fingerprint(),
            target_triple: format!("{}-{}", std::env::consts::ARCH, std::env::consts::OS),
        };
        let header_bytes =
            bincode::serialize(&header).map_err(|e| format!("header serialize: {}", e))?;

        let mut buf = Vec::new();
        buf.extend_from_slice(AOT_ARCHIVE_MAGIC);
        buf.extend_from_slice(&(header_bytes.len() as u32).to_le_bytes());
        buf.extend_from_slice(&header_bytes);
        buf.extend_from_slice(&toc_bytes);
        buf.extend_from_slice(&code_section);

        Ok(buf)
    }

    /// Seed this builder with entries from an existing archive, keeping models
    /// that are not overridden by new `add_model` calls. Call this before
    /// `add_model` so that new entries take precedence.
    pub fn merge_from_existing(&mut self, archive: &AotArchive) {
        let existing_names: std::collections::HashSet<String> =
            self.entries.iter().map(|(e, _)| e.model_name.clone()).collect();
        for entry in &archive.toc {
            if existing_names.contains(&entry.model_name) {
                continue;
            }
            if let Some(code) = archive.get_code(&entry.codegen_key_hash) {
                self.entries.push((entry.clone(), code.to_vec()));
            }
        }
    }

    /// Load the default archive (if it exists), merge into this builder, then
    /// write the combined result back.  New models added via `add_model` before
    /// this call take precedence over entries with the same name in the old archive.
    pub fn write_merged_to_default(self) -> Result<(), String> {
        self.write_merged_for_scope(CacheScope::Project)
    }

    /// Merge with existing tier archive at [`AotArchive::archive_path_for_scope`], then write.
    pub fn write_merged_for_scope(mut self, scope: CacheScope) -> Result<(), String> {
        let path = AotArchive::archive_path_for_scope(scope)
            .ok_or_else(|| "no archive path for scope".to_string())?;
        if let Some(dir) = path.parent() {
            let legacy = dir.join(AOT_ARCHIVE_LEGACY);
            if legacy.is_file() && legacy != path {
                if let Ok(old) = AotArchive::load(&legacy) {
                    self.merge_from_existing(&old);
                }
            }
        }
        if path.is_file() {
            if let Ok(old) = AotArchive::load(&path) {
                self.merge_from_existing(&old);
            }
        }
        self.write_to_file(&path)
    }
}

/// Try to load the default AOT archive from the cache directory.
pub fn try_load_default_archive() -> Option<AotArchive> {
    let path = AotArchive::default_archive_path()?;
    match AotArchive::load(&path) {
        Ok(a) => Some(a),
        Err(e) => {
            eprintln!("[aot] skip default archive ({}): {}", path.display(), e);
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn archive_rejects_foreign_binary_fingerprint() {
        let mut builder = AotArchive::new_builder();
        builder.add_model(
            "TestModel",
            "hash-00-ok",
            vec![0x90u8; 32],
            vec![],
            0,
            0,
        );
        let bytes = builder.build().expect("build archive");

        // Round-trip with the current binary fingerprint succeeds.
        let _ = AotArchive::from_bytes(&bytes).expect("current-binary archive loads");

        // Mutate the header to simulate an archive written by a different binary.
        let mut tampered = bytes.clone();
        let header_len_bytes: [u8; 4] = tampered[8..12].try_into().unwrap();
        let header_len = u32::from_le_bytes(header_len_bytes) as usize;
        let mut header: AotArchiveHeader =
            bincode::deserialize(&tampered[12..12 + header_len]).unwrap();
        header.compiler_version = "0.0.0|bin:deadbeefdeadbeef".to_string();
        let new_header_bytes = bincode::serialize(&header).unwrap();
        // Replacing the header bytes is only safe when lengths line up; pad with spaces
        // in `compiler_version` above isn't needed because `bincode` is length-prefixed per
        // field and our replacement re-encodes the full header.
        let mut rebuilt = Vec::new();
        rebuilt.extend_from_slice(AOT_ARCHIVE_MAGIC);
        rebuilt.extend_from_slice(&(new_header_bytes.len() as u32).to_le_bytes());
        rebuilt.extend_from_slice(&new_header_bytes);
        let toc_end = 12 + header_len;
        rebuilt.extend_from_slice(&tampered[toc_end..]);
        tampered = rebuilt;

        match AotArchive::from_bytes(&tampered) {
            Ok(_) => panic!("foreign compiler_version must be rejected"),
            Err(e) => assert!(
                e.contains("compiler version mismatch"),
                "unexpected error: {e}"
            ),
        }
    }
}
